output_path = "/tmp/"
target_yield = 100000000000
pore_type = "R10"
nucleotide_type = "DNA"

[parameters]
sample_name = "test"
experiment_name = "test_2_bacteria"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"
sample_rate = 5000

[[sample]]
name = "Bacteria 1"
input_genome = "/squiggle_arrs/mixed_ref.fa"
mean_read_length = 1000
weight = 1

# [[sample]]
# name = "Bacteria 2"
# input_genome = "docker/squiggle_arrs/mixed_ref.fa"
# mean_read_length = 1500
# weight = 2
