output_path = "/tmp/"
random_seed = 11
target_yield = 18602483900
working_pore_percent = 85
pore_type = "R10"

[parameters]
experiment_name = "icarust_paper_data"
sample_name = "control_icarust_R10"
flowcell_name = "FAWFAKE3"
experiment_duration_set = 6000
device_id = "FAKE_MINION"
position = "MS00000"
break_read_ms = 1000

[[sample]]
name = "humanHG38"
weight = 1
input_genome = "/squiggle_arrs/hg38_no_alts.part_NC_000020.11 Homo sapiens chromosome 20, GRCh38.p14 Primary Assembly.fa.gz"
mean_read_length = 2800
barcodes = ["Barcode01", "Barcode02", "Barcode03"]
barcode_weights = [1, 2, 3]