output_path = "/tmp/"
random_seed = 11
target_yield = 18602483900
working_pore_percent = 85
pore_type = "R10"

[parameters]
experiment_name = "icarust_paper_data"
sample_name = "control_icarust_R10"
flowcell_name = "FAWFAKE3"
experiment_duration_set = 6000
device_id = "FAKE_MINION"
position = "MS00000"
break_read_ms = 1000

[[sample]]
name = "r10_bac"
weight = 1
input_genome = "/squiggle_arrs/mixed_ref.fa"
mean_read_length = 2800
