
[caller_settings.guppy]
config = "dna_r10.4.1_e8.2_400bps_hac"
address = "ipc:///tmp/.guppy/5555"
debug_log = "icarust_playback_adaptive.fq"

[mapper_settings.mappy_rs]
fn_idx_in = "path/to/mapping_index"
debug_log = "icarust_playback_adaptive.paf"

[[regions]]
name = "select_chr_21_22"
min_chunks = 1
max_chunks = 4
targets = ["NC_000020.11", "NC_000021.9"]
single_off = "unblock"
multi_off = "unblock"
single_on = "stop_receiving"
multi_on = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"