output_path = "/tmp/"
target_yield = 100000000000
working_pore_percent = 85

[parameters]
sample_name = "test-cdna"
experiment_name = "titin"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"

[[sample]]
name = "Bacteria 1"
input_genome = "squiggle_arrs/ENST00000589042.5.squiggle.npy"
mean_read_length = 20000
weight = 1
