output_path = "/data/satrio/tmp/"
target_yield = 100000000000
working_pore_percent = 85
pore_type = "R10"
analyte_type = "RNA"

[parameters]
sample_name = "test"
experiment_name = "test_transcript"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"

[[sample]]
name = "Human"
#input_genome = "/data/satrio/test-icarust-as/gencode.v44.transcripts.chr17.fa"
input_genome = "/data/satrio/test-icarust-as/transcript.tp53.fa"
mean_read_length = 3000
weight = 1
amplicon = true
