output_path = "/tmp/"

[parameters]
sample_name = "test"
experiment_name = "test_2_bacteria"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "Bantersaurus"
position = "FenceSitter"

[[sample]]
input_genome = "squiggle_arrs/monkeypox/"
mean_read_length = 20000
amplicon = true
barcodes = ["Barcode01", "Barcode02", "Barcode03"]
barcode_weights = [1, 2, 3]
uneven = true
